=== sadrians/st26proto_1/authoringtool/sequencelistings/static/sequencelistings/st26.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:group name="applicantNameGroup">
        <xs:sequence>
            <xs:element name="ApplicantName">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="languageCode"
                                          type="xs:string"
                                          use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
    
            <xs:element name="ApplicantNameLatin" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:group>
    
    <xs:group name="applicationIdentificationGroup">
        <xs:sequence>
            <xs:element name="IPOfficeCode"/>
            <xs:element name="ApplicationNumberText"/>
            <xs:element name="FilingDate" minOccurs="0"/>    
        </xs:sequence>
    </xs:group>
                
    <xs:element name="ST26SequenceListing">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="2"
                           minOccurs="1">
                    <xs:element name="ApplicationIdentification"
                                maxOccurs="1"
                                minOccurs="0">
                        <xs:complexType>
                            <xs:group ref="applicationIdentificationGroup"/>
                        </xs:complexType>
                        <!-- <xs:complexType>
                            <xs:sequence>
                                <xs:element name="IPOfficeCode" type="xs:string"/>
                                <xs:element name="ApplicationNumberText" type="xs:string"/>
                                <xs:element name="FilingDate" type="xs:string"/>
                            </xs:sequence>
                        </xs:complexType> -->
                    </xs:element>
                    
                    <xs:element name="ApplicantFileReference"
                                type="xs:string"
                                maxOccurs="1"
                                minOccurs="0" />
                </xs:choice>
                
                <xs:element name="EarliestPriorityApplicationIdentification">
                    <xs:complexType>
                        <xs:group ref="applicationIdentificationGroup"/>
                    </xs:complexType>
                    <!-- <xs:complexType>
                        <xs:sequence>
                            <xs:element name="IPOfficeCode" type="xs:string"/>
                            <xs:element name="ApplicationNumberText" type="xs:string"/>
                            <xs:element name="FilingDate" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType> -->
                </xs:element>
                <xs:group ref="applicantNameGroup" minOccurs="0"/>
                
                <!-- <xs:group name="applicantNameGroup" minOccurs="0">
                    <xs:sequence>
                        <xs:element name="ApplicantName">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="languageCode"
                                                      type="xs:string"
                                                      use="required"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
        
                        <xs:element name="ApplicantNameLatin" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:group> -->

                <xs:element name="InventorName">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="languageCode"
                                              type="xs:string"
                                              use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="InventorNameLatin" type="xs:string"/>

                <xs:element name="InventionTitle"   maxOccurs="unbounded"
                                                    minOccurs="1">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="languageCode"
                                              type="xs:string"
                                              use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="SequenceTotalQuantity"
                            type="xs:string" />

                <xs:element
                        name="SequenceData"
                        maxOccurs="unbounded"
                        minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="INSDSeq">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="INSDSeq_length" type="xs:string"/>

                                        <xs:element name="INSDSeq_moltype">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="DNA"/>
                                                    <xs:enumeration value="RNA"/>
                                                    <xs:enumeration value="AA"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                        <xs:element name="INSDSeq_division"
                                                    type="xs:string"
                                                    fixed="PAT"/>

                                        <xs:element name="INSDSeq_other-seqids">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="INSDSeqid" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="INSDSeq_feature-table">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="INSDFeature"
                                                                maxOccurs="unbounded"
                                                                minOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="INSDFeature_key" type="featureKeyValue"/>
                                                                <xs:element name="INSDFeature_location" type="xs:string"/>
                                                                <xs:element name="INSDFeature_quals"
                                                                            maxOccurs="1"
                                                                            minOccurs="0">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="INSDQualifier"
                                                                                        maxOccurs="unbounded"
                                                                                        minOccurs="1">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element
                                                                                                name="INSDQualifier_name"
                                                                                                type="xs:string"/>
                                                                                        <xs:element
                                                                                                name="INSDQualifier_value"
                                                                                                type="xs:string"
                                                                                                maxOccurs="1"
                                                                                                minOccurs="0"/>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>

                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="INSDSeq_sequence" type="xs:string"/>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sequenceIDNumber"
                                      type="xs:string"
                                      use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
            <xs:attribute name="dtdVersion" type="xs:string" use="required"/>
            <xs:attribute name="fileName" type="xs:string" />
            <xs:attribute name="softwareName" type="xs:string" />
            <xs:attribute name="softwareVersion" type="xs:string" />
            <xs:attribute name="productionDate" type="xs:string" />
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="featureKeyValue">
        <xs:restriction base="xs:string">
            <xs:enumeration value="allele"/>
            <xs:enumeration value="attenuator"/>
            <xs:enumeration value="C_region"/>
            <xs:enumeration value="CAAT_signal"/>
            <xs:enumeration value="CDS"/>
            <xs:enumeration value="conflict"/>
            <xs:enumeration value="D-loop"/>
            <xs:enumeration value="D_segment"/>
            <xs:enumeration value="enhancer"/>
            <xs:enumeration value="exon"/>
            <xs:enumeration value="GC_signal"/>
            <xs:enumeration value="gene"/>
            <xs:enumeration value="iDNA"/>
            <xs:enumeration value="intron"/>
            <xs:enumeration value="J_segment"/>
            <xs:enumeration value="LTR"/>
            <xs:enumeration value="mat_peptide"/>
            <xs:enumeration value="misc_binding"/>
            <xs:enumeration value="misc_difference"/>
            <xs:enumeration value="misc_feature"/>
            <xs:enumeration value="misc_recomb"/>
            <xs:enumeration value="misc_RNA"/>
            <xs:enumeration value="misc_signal"/>
            <xs:enumeration value="misc_structure"/>
            <xs:enumeration value="modified_base"/>
            <xs:enumeration value="mRNA"/>
            <xs:enumeration value="mutation"/>
            <xs:enumeration value="N_region"/>
            <xs:enumeration value="old_sequence"/>
            <xs:enumeration value="polyA_signal"/>
            <xs:enumeration value="polyA_site"/>
            <xs:enumeration value="precursor_RNA"/>
            <xs:enumeration value="prim_transcript"/>
            <xs:enumeration value="primer_bind"/>
            <xs:enumeration value="promoter"/>
            <xs:enumeration value="protein_bind"/>
            <xs:enumeration value="RBS"/>
            <xs:enumeration value="repeat_region"/>
            <xs:enumeration value="repeat_unit"/>
            <xs:enumeration value="rep_origin"/>
            <xs:enumeration value="rRNA"/>
            <xs:enumeration value="S_region"/>
            <xs:enumeration value="satellite"/>
            <xs:enumeration value="scRNA"/>
            <xs:enumeration value="sig_peptide"/>
            <xs:enumeration value="snRNA"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="stem_loop"/>
            <xs:enumeration value="STS"/>
            <xs:enumeration value="TATA_signal"/>
            <xs:enumeration value="terminator"/>
            <xs:enumeration value="transit_peptide"/>
            <xs:enumeration value="tRNA"/>
            <xs:enumeration value="unsure"/>
            <xs:enumeration value="V_region"/>
            <xs:enumeration value="V_segment"/>
            <xs:enumeration value="variation"/>
            <xs:enumeration value="3'clip"/>
            <xs:enumeration value="3'UTR"/>
            <xs:enumeration value="5'clip"/>
            <xs:enumeration value="5'UTR"/>
            <xs:enumeration value="-10_signal"/>
            <xs:enumeration value="-35_signal"/>
            <xs:enumeration value="ACT_SITE"/>
            <xs:enumeration value="BINDING"/>
            <xs:enumeration value="CA_BIND"/>
            <xs:enumeration value="CARBOHYD"/>
            <xs:enumeration value="CHAIN"/>
            <xs:enumeration value="COILED"/>
            <xs:enumeration value="COMPBIAS"/>
            <xs:enumeration value="CONFLICT"/>
            <xs:enumeration value="CROSSLNK"/>
            <xs:enumeration value="DISULFID"/>
            <xs:enumeration value="DNA_BIND"/>
            <xs:enumeration value="DOMAIN"/>
            <xs:enumeration value="HELIX"/>
            <xs:enumeration value="INIT_MET"/>
            <xs:enumeration value="INTRAMEM"/>
            <xs:enumeration value="LIPID"/>
            <xs:enumeration value="METAL"/>
            <xs:enumeration value="MOD_RES"/>
            <xs:enumeration value="MOTIF"/>
            <xs:enumeration value="MUTAGEN"/>
            <xs:enumeration value="NON_STD"/>
            <xs:enumeration value="NON_TER"/>
            <xs:enumeration value="NP_BIND"/>
            <xs:enumeration value="PEPTIDE"/>
            <xs:enumeration value="PROPEP"/>
            <xs:enumeration value="REGION"/>
            <xs:enumeration value="REPEAT"/>
            <xs:enumeration value="SIGNAL"/>
            <xs:enumeration value="SITE"/>
            <xs:enumeration value="SOURCE"/>
            <xs:enumeration value="STRAND"/>
            <xs:enumeration value="TOPO_DOM"/>
            <xs:enumeration value="TRANSMEM"/>
            <xs:enumeration value="TRANSIT"/>
            <xs:enumeration value="TURN"/>
            <xs:enumeration value="UNSURE"/>
            <xs:enumeration value="VARIANT"/>
            <xs:enumeration value="VAR_SEQ"/>
            <xs:enumeration value="ZN_FING"/>         
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== sadrians/st26proto_1/authoringtool/sequencelistings/static/sequencelistings/test_xmlsql.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ST26SequenceListing PUBLIC "-//WIPO//DTD Sequence Listing 1.0//EN" "ST26SequenceListing_V1_0.dtd">
<?xml-stylesheet type="text/xsl" href="st26.xsl"?>
<ST26SequenceListing dtdVersion="1" 
                    fileName="test_xmlsql"
                    softwareName="prototype" 
                    softwareVersion="0.1"
                    productionDate="Feb. 18, 2016">
<!-- <ST26SequenceListing dtdVersion="1" 
                    fileName="test_xmlsql"
                    softwareName="prototype" 
                    softwareVersion="0.1"
                    productionDate="Feb. 19, 2016, 12:54 a.m."
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="st26.xsd"> -->
    <ApplicationIdentification>
        <IPOfficeCode>EP</IPOfficeCode>
        <ApplicationNumberText>2015123456</ApplicationNumberText>
        <FilingDate>Feb. 18, 2016</FilingDate>
    </ApplicationIdentification>
    <ApplicantFileReference>123</ApplicantFileReference>
    <EarliestPriorityApplicationIdentification>
        <IPOfficeCode>US</IPOfficeCode>
        <ApplicationNumberText>998877</ApplicationNumberText>
        <FilingDate>Feb. 18, 2016</FilingDate>
    </EarliestPriorityApplicationIdentification>
    <ApplicantName languageCode="EN">
        John Smith
    </ApplicantName>
    <ApplicantNameLatin>
        same
    </ApplicantNameLatin>
    <InventorName languageCode="FR">
        Mary Dupont
    </InventorName>
    <InventorNameLatin>
        Mary Dupont
    </InventorNameLatin>
    
        <InventionTitle languageCode="EN">
            Invention 1
        </InventionTitle>
    
    
    <SequenceTotalQuantity>
        1
    </SequenceTotalQuantity>
    
        <SequenceData sequenceIDNumber="1">
            <INSDSeq>
                <INSDSeq_length>18</INSDSeq_length>
                <INSDSeq_moltype>DNA</INSDSeq_moltype>
                <INSDSeq_division>PAT</INSDSeq_division>
                <INSDSeq_other-seqids>
                    <INSDSeqid>-</INSDSeqid>
                </INSDSeq_other-seqids>
                <INSDSeq_feature-table>
                    
                </INSDSeq_feature-table>
                <INSDSeq_sequence>catcatcatcatcatcat</INSDSeq_sequence>
            </INSDSeq>
        </SequenceData>
      
</ST26SequenceListing>

=== sadrians/st26proto_1/authoringtool/sequencelistings/static/sequencelistings/file2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ST26SequenceListing PUBLIC "-//WIPO//DTD Sequence Listing 1.0//EN" "ST26SequenceListing_V1_0.dtd">
<?xml-stylesheet type="text/xsl" href="st26.xsl"?>
<ST26SequenceListing dtdVersion="1.0" 
                    fileName="file2"
                    softwareName="ST26 authoring tool prototype" 
                    softwareVersion="0.1"
                    productionDate="Feb. 2, 2016">
<!-- <ST26SequenceListing dtdVersion="1.0" 
                    fileName="file2"
                    softwareName="ST26 authoring tool prototype" 
                    softwareVersion="0.1"
                    productionDate="Feb. 2, 2016, 10:47 p.m."
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="st26.xsd"> -->
    <ApplicationIdentification>
        <IPOfficeCode>EP</IPOfficeCode>
        <ApplicationNumberText>1299887766.5</ApplicationNumberText>
        <FilingDate>Aug. 3, 2014</FilingDate>
    </ApplicationIdentification>
    <ApplicantFileReference>WO123</ApplicantFileReference>
    <EarliestPriorityApplicationIdentification>
        <IPOfficeCode>JP</IPOfficeCode>
        <ApplicationNumberText>54545454</ApplicationNumberText>
        <FilingDate>Dec. 29, 2013</FilingDate>
    </EarliestPriorityApplicationIdentification>
    <ApplicantName languageCode="EN">
        applicant2
    </ApplicantName>
    <ApplicantNameLatin>
        applicant2
    </ApplicantNameLatin>
    <InventorName languageCode="EN">
        inventor2
    </InventorName>
    <InventorNameLatin>
        inventor2
    </InventorNameLatin>
    
        <InventionTitle languageCode="EN">
            title3
        </InventionTitle>
    
        <InventionTitle languageCode="JP">
            title4
        </InventionTitle>
    
    
    <SequenceTotalQuantity>
        2
    </SequenceTotalQuantity>
    
        <SequenceData sequenceIDNumber="1">
            <INSDSeq>
                <INSDSeq_length>30</INSDSeq_length>
                <INSDSeq_moltype>DNA</INSDSeq_moltype>
                <INSDSeq_division>PAT</INSDSeq_division>
                <INSDSeq_other-seqids>
                    <INSDSeqid>-</INSDSeqid>
                </INSDSeq_other-seqids>
                <INSDSeq_feature-table>
                    
                        <INSDFeature>
                            <INSDFeature_key>source</INSDFeature_key>
                            <INSDFeature_location>1..30</INSDFeature_location>
                            <INSDFeature_quals>
                                
                                <INSDQualifier>
                                    <INSDQualifier_name>organism</INSDQualifier_name>
                                    <INSDQualifier_value>homo sapiens</INSDQualifier_value>
                                </INSDQualifier>
                                
                                <INSDQualifier>
                                    <INSDQualifier_name>mol_type</INSDQualifier_name>
                                    <INSDQualifier_value>genomic DNA</INSDQualifier_value>
                                </INSDQualifier>
                                
                            </INSDFeature_quals>
                        </INSDFeature>
                    
                        <INSDFeature>
                            <INSDFeature_key>allele</INSDFeature_key>
                            <INSDFeature_location>4..6</INSDFeature_location>
                            <INSDFeature_quals>
                                
                            </INSDFeature_quals>
                        </INSDFeature>
                    
                </INSDSeq_feature-table>
                <INSDSeq_sequence>agtcncttagggacccaacactttcattca</INSDSeq_sequence>
            </INSDSeq>
        </SequenceData>
    
        <SequenceData sequenceIDNumber="2">
            <INSDSeq>
                <INSDSeq_length>5</INSDSeq_length>
                <INSDSeq_moltype>AA</INSDSeq_moltype>
                <INSDSeq_division>PAT</INSDSeq_division>
                <INSDSeq_other-seqids>
                    <INSDSeqid>-</INSDSeqid>
                </INSDSeq_other-seqids>
                <INSDSeq_feature-table>
                    
                        <INSDFeature>
                            <INSDFeature_key>SOURCE</INSDFeature_key>
                            <INSDFeature_location>1..5</INSDFeature_location>
                            <INSDFeature_quals>
                                
                                <INSDQualifier>
                                    <INSDQualifier_name>ORGANISM</INSDQualifier_name>
                                    <INSDQualifier_value>mus</INSDQualifier_value>
                                </INSDQualifier>
                                
                                <INSDQualifier>
                                    <INSDQualifier_name>MOL_TYPE</INSDQualifier_name>
                                    <INSDQualifier_value>protein</INSDQualifier_value>
                                </INSDQualifier>
                                
                            </INSDFeature_quals>
                        </INSDFeature>
                    
                        <INSDFeature>
                            <INSDFeature_key>VARIATION</INSDFeature_key>
                            <INSDFeature_location>3</INSDFeature_location>
                            <INSDFeature_quals>
                                
                            </INSDFeature_quals>
                        </INSDFeature>
                    
                </INSDSeq_feature-table>
                <INSDSeq_sequence>MTERT</INSDSeq_sequence>
            </INSDSeq>
        </SequenceData>
      
</ST26SequenceListing>

=== sadrians/st26proto_1/authoringtool/sequencelistings/static/sequencelistings_output/Berthold1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ST26SequenceListing PUBLIC "-//WIPO//DTD Sequence Listing 1.0//EN" "ST26SequenceListing_V1_0.dtd">
<?xml-stylesheet type="text/xsl" href="st26.xsl"?>
<ST26SequenceListing dtdVersion="1" 
                    fileName="Berthold1"
                    softwareName="prototype" 
                    softwareVersion="0.1"
                    productionDate="Feb. 3, 2016">
<!-- <ST26SequenceListing dtdVersion="1" 
                    fileName="Berthold1"
                    softwareName="prototype" 
                    softwareVersion="0.1"
                    productionDate="Feb. 3, 2016, 11:32 p.m."
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="st26.xsd"> -->
    <ApplicationIdentification>
        <IPOfficeCode>EP</IPOfficeCode>
        <ApplicationNumberText>sdf</ApplicationNumberText>
        <FilingDate>Jan. 1, 2015</FilingDate>
    </ApplicationIdentification>
    <ApplicantFileReference>xxx</ApplicantFileReference>
    <EarliestPriorityApplicationIdentification>
        <IPOfficeCode>EP</IPOfficeCode>
        <ApplicationNumberText>ep552668</ApplicationNumberText>
        <FilingDate>Jan. 1, 2014</FilingDate>
    </EarliestPriorityApplicationIdentification>
    <ApplicantName languageCode="sd">
        sdf
    </ApplicantName>
    <ApplicantNameLatin>
        sdfd
    </ApplicantNameLatin>
    <InventorName languageCode="sd">
        sdfsd
    </InventorName>
    <InventorNameLatin>
        sdf
    </InventorNameLatin>
    
        <InventionTitle languageCode="EN">
            Test_Berthold
        </InventionTitle>
    
    
    <SequenceTotalQuantity>
        1
    </SequenceTotalQuantity>
    
        <SequenceData sequenceIDNumber="1">
            <INSDSeq>
                <INSDSeq_length>11</INSDSeq_length>
                <INSDSeq_moltype>AA</INSDSeq_moltype>
                <INSDSeq_division>PAT</INSDSeq_division>
                <INSDSeq_other-seqids>
                    <INSDSeqid>-</INSDSeqid>
                </INSDSeq_other-seqids>
                <INSDSeq_feature-table>
                    
                        <INSDFeature>
                            <INSDFeature_key>SOURCE</INSDFeature_key>
                            <INSDFeature_location>1..11</INSDFeature_location>
                            <INSDFeature_quals>
                                
                                <INSDQualifier>
                                    <INSDQualifier_name>ORGANISM</INSDQualifier_name>
                                    <INSDQualifier_value>Homo sapiens</INSDQualifier_value>
                                </INSDQualifier>
                                
                                <INSDQualifier>
                                    <INSDQualifier_name>MOL_TYPE</INSDQualifier_name>
                                    <INSDQualifier_value>protein</INSDQualifier_value>
                                </INSDQualifier>
                                
                            </INSDFeature_quals>
                        </INSDFeature>
                    
                </INSDSeq_feature-table>
                <INSDSeq_sequence>gratarecase</INSDSeq_sequence>
            </INSDSeq>
        </SequenceData>
      
</ST26SequenceListing>
